### ISSUE TITLE
Help in implementation of Diverse Beam Search

### ISSUE THREAD

**Issue by PlaeryinBol** [TaiseiAso/BiGruAttEncDec#2]
Hello! I found your repository with DBS implementation, can I ask you for help on replacing my default BS (with LSTM-decoder) with a DBS?

**Comment by TaiseiAso** [comment]
Sorry it took me so long to reply.
I implemented "Group Diverse Beam Search (GROUPBS)" and "Sibling Diverse Beam Search (SIBLINGBS)" in DBS.

GROUPBS: https://arxiv.org/abs/1610.02424
SIBLINGBS: https://arxiv.org/abs/1601.00372

GROUPBS parallels G beam search groups of width B. Each beam search group penalizes the generation of words generated by others at the same time. (Ignore finished beam search groups.)
https://github.com/TaiseiAso/BiGruAttEncDec/blob/a4745f98e0f191854571b0a6a183e72300f47320/decode.py#L213-L217

SIBLINGBS penalizes beams derived from the same beam in rank order.
https://github.com/TaiseiAso/BiGruAttEncDec/blob/a4745f98e0f191854571b0a6a183e72300f47320/decode.py#L232

DBS will exit when all beam search groups have exited.
Sorry for my poor English.

**Comment by PlaeryinBol** [comment]
Many thanks, I will try it!
